<?php

namespace studioespresso\exporter\migrations;

use craft\db\Migration;
use studioespresso\exporter\records\ExportRecord;

class m250730_110551_add_condition_config extends Migration
{
    /**
     * @inheritdoc
     */
    public function safeUp(): bool
    {
        $this->addColumn(ExportRecord::tableName(), 'conditionConfig', $this->mediumText());

        return true;
    }

    public function safeDown()
    {
        $this->dropTableIfExists(ExportRecord::tableName());
        parent::safeDown(); // TODO: Change the autogenerated stub
    }
}
